name: deploy-api

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        # Finds a specific version of Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '14.17'
        # Install dependencies
      - run: npm ci
        # Build project
      - run: npm run build
        # Create env file
      - run: |
          touch .env
          echo API_WEATHER_KEY=${{ secrets.API_WEATHER_KEY }} >> .env
          echo APP_HOST=${{ secrets.APP_HOST }} >> .env
          echo APP_PORT=${{ secrets.APP_PORT }} >> .env
        # Deploy project
      - uses: appleboy/scp-action@v0.1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          overwrite: true
          source: "dist,node_modules,.env"
          target: "projects/api"
